trigger:
  branches:
    include:
    - main
  paths:
    include:
    - PackerHCL/Trigger/*
 
schedules:
- cron: "0 4 12-18 * 6"
  displayName: Monthly Saturday build
  branches:
    include:
    - main
  always: true

 
pool:
 
  name: PackerHCL_Pool
 
steps:
 
- task: CopyFiles@2
 
  displayName: 'Copy Packer Files to Artifacts'
 
  inputs:
 
    SourceFolder: PackerHCL
 
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    cleanTargetFolder: true
 
 
 
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: PackerConfig